# Generated by Django 5.2.17 on 2026-10-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hostel_type', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('rent', models.IntegerField()),
                ('available_beds', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
