# Generated by Django 5.2.17 on 2026-10-06 05:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hostel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='distance',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AddField(
            model_name='hostel',
            name='food_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostel',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='hostel',
            name='total_beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='available_beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_type',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls')], max_length=10),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
